Improve test output

diff --git a/tests/test-utils b/tests/test-utils
--- a/tests/test-utils
+++ b/tests/test-utils
@@ -4,6 +4,15 @@
 # This builtin only works in real completions, so stub it for the tests
 compopt() { true; }
 
+begin-test-suite() {
+    print-binary-versions
+    echo
+}
+
+end-test-suite() {
+    true
+}
+
 begin-test() {
     echo "TEST: $1"
 }
@@ -11,23 +20,20 @@ begin-test() {
 end-test() {
     local status=$?
     if [[ $status -eq 0 ]]; then
-        echo 'PASS'
+        echo '  PASS'
         echo
     else
         if [[ -n $_TEST_BINARIES ]]; then
             echo
-            local bin
-            for bin in "${_TEST_BINARIES[@]}"; do
-                "$bin" --version
-            done
+            print-binary-versions
         fi
         exit $status
     fi
 }
 
 test-completion() {
-    print-array 'RUNNING TEST:       ' "$@"
-    _COMPLETION_TEST=($@)
+    _COMPLETION_TEST=($@⇥)
+    print-array '  INPUT:' "${_COMPLETION_TEST[@]}"
     COMP_WORDS=($@)
     COMP_CWORD=$(($# - 1))
     COMP_LINE="$*"
@@ -36,35 +42,35 @@ test-completion() {
 }
 
 expect() {
-    print-array 'EXPECTED RESULT:    ' "$@"
+    print-array '  EXPECTED RESULT:' "$@"
     local word
     for word in "$@"; do
         if ! [[ " ${COMPREPLY[@]} " =~ " $word " ]]; then
-            echo 'Completion failed!'
-            print-array '  Command:   ' "${_COMPLETION_TEST[@]}"
-            print-array '  Output:    ' "${COMPREPLY[@]}"
-            echo "  Missing:    $(printf "%q" "$word")"
+            echo '    Expectation failed!'
+            print-array '    Output:' "${COMPREPLY[@]}"
+            if [[ -n $COMPREPLY ]]; then
+                echo "    Missing:    $(printf "%q" "$word")"
+            fi
             exit 1
         fi >&2
     done
 }
 
 reject() {
-    print-array 'SHOULD NOT INCLUDE: ' "$@"
+    print-array '  SHOULD NOT INCLUDE:' "$@"
     local word
     for word in "$@"; do
         if [[ " ${COMPREPLY[@]} " =~ " $word " ]]; then
-            echo 'Completion failed!'
-            print-array '  Command:   ' "${_COMPLETION_TEST[@]}"
-            print-array '  Output:    ' "${COMPREPLY[@]}"
-            echo "  Unexpected: $(printf "%q" "$word")"
+            echo '    Expectation failed!'
+            print-array '    Output:' "${COMPREPLY[@]}"
+            echo "    Unexpected: $(printf "%q" "$word")"
             exit 1
         fi >&2
     done
 }
 
 print-array() {
-    echo -n "$1"
+    printf '%-22s' "$1"
     if [[ $# -eq 1 ]]; then
         echo ' (empty)'
         return
@@ -74,4 +80,12 @@ print-array() {
         printf ' %q' "$1"
     done
     echo
+}
+
+print-binary-versions() {
+    echo 'Versions:'
+    local bin
+    for bin in "${_TEST_BINARIES[@]}"; do
+        "$bin" --version || echo "`$bin --version` failed with status $?" >&2
+    done
 }
